logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:h2:file:///./productdb
management:
  endpoints:
    web:
      exposure:
        include: "actuator,health,prometheus"