logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8082
spring:
  application:
    name: inventory-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  r2dbc:
    url: r2dbc:h2:file:///./testdb
management:
  endpoints:
    web:
      exposure:
        include: "*"