logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
#            discovery:
#                locator:
#                    enabled: true
#                    lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: "actuator,health,prometheus"